apiVersion: apps/v1
kind: Deployment
metadata:
  name: openelb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openelb
  template:
    metadata:
      labels:
        app: openelb
    spec:
      containers:
        - image: luksa/kubia
          name: kubia
          ports:
            - containerPort: 8080
